<?php

function dna_menu() {
    $items['dna_input'] = array(
        'title' => 'DNA string input',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_success'] = array(
        'title' => 'Here is your pair',
        'page callback' => 'dna_display',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['input_dna_string'] = array(
        '#title' => 'Input Date',
        '#type' => 'textfield',
        '#description' => t("Input only ACGT, to find corresponding base pair"),
        '#element_validate' => array('element_validate_base')
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Find Pairs',
    );

    return $form;
}

function element_validate_base($element) {
    //splits string for easier validation
    $split = str_split($element['#value']);
    print_r($split);
    $reference = array('A', 'a', 'C', 'c', 'G', 'g', 'T', 't');
    foreach ($split as $base) {
        //if there are no matches between input and reference array, display
        //error
        if (!in_array($base, $reference)) {
            form_error($element, t('Only A, C, G, or T allowed'));
        }
    }
}

function dna_form_submit($form, &$form_state) {
    $input_dna_string = $form_state['values']['input_dna_string'];
    $result = dna_transform($input_dna_string);
    $_SESSION['dna_results'] = $result;
    $form_state['redirect'] = 'dna_success';
}

function dna_transform($dna_string) {
    $output_base_pairs = "";
    $split_string = str_split($dna_string);
    //splits string into array and evaluates the value of each array item
    //pushes complimentary pair to new array
    foreach ($split_string as $base_pair) {
        if ($base_pair == 'A' || $base_pair == 'a') {
            $output_base_pairs .= 'T';
        } elseif ($base_pair == 'T' || $base_pair == 't') {
            $output_base_pairs .= 'A';
        } elseif ($base_pair == 'G' || $base_pair == 'g') {
            $output_base_pairs .= 'C';
        } else {
            $output_base_pairs .= 'G';
        }
    }
    return $output_base_pairs;
}

function dna_display() {
    $output = $_SESSION['dna_results'];
    return "<h2>".$output."</h2>";
}
